version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: task-management-db
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: task-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
